### ISSUE TITLE
remove top menu

### ISSUE THREAD

**Issue by Rupinderwadali** [Rupinderwadali/My-site#1]

**Comment by Rupinderwadali** [comment]
I remove the top menu which repetend the navbar from header.php file.

**Comment by shaina7837** [comment]
repetend? 
Please read the comment before submitting.

**Comment by Rupinderwadali** [comment]
repetend means a repeated navbar that shown with social icons on header. Is anything wrong with this?

**Comment by Rupinderwadali** [comment]
Its completed
