### ISSUE TITLE
Categorize post according to area 

### ISSUE THREAD

**Issue by Rupinderwadali** [Rupinderwadali/My-site#7]

**Comment by Rupinderwadali** [comment]
I categories the post according to area after creating new taxonomy. And I also add a piece of code to query by taxonomy to pull the posts that have particular area in them. But I am failed to do that. It's not working I don't no why.

**Comment by shaina7837** [comment]
*don't know
Is this problem solved now?

**Comment by Rupinderwadali** [comment]
Yes, it had been solved. But I have deleted all the work by mistake when I update theme and I didn't have the backup of my work on github unfortunately. So I am still working on it.

**Comment by Rupinderwadali** [comment]
Yes, now its solved with the help of following code. Add the following code in template. Here "area" is taxonomy and "Chheharta" is custom taxonomy whose posts is to be displayed when select id "areas" change and user click on the "Chheharta" option of drop-down. 
<div class="area">
<?php
$terms = get_terms('area');
foreach($terms as $term) : ?>
        <div class = "<?php echo $term->name ?>">
                <?php
                $posts = new WP_Query(array('area' => $term->slug));

                if( $posts->have_posts() ):
                        while( $posts->have_posts() ) :
                                $posts->the_post();
                                the_post_thumbnail();?>
        <div class="post_title">
                <a href ="<?php the_permalink();?>"><?php the_title();?></a>
        </div>
                <?php
                        endwhile;
                endif;
                ?>
        </div>
<?php
endforeach; ?>

<?php //wp_reset_postdata();
?>
</div>
Now call this template in index.php file or other where you want to show your posts with the following code within the loop:
<?php
           get_template_part( 'content', 'area' );
?>
And using jquery we can show the posts when we select the option from dropdown
<script type="text/javascript"  language="javascript">    
     $("#areas").change(function(){
                console.log("running");
                var select= this.value;
                $(".area").children().css({"display":"none"});
                        if(select == 'Chheharta'){
                             $(".Chheharta").css({"display": "block"});
                     }
     });
</script>

**Comment by Rupinderwadali** [comment]
Thanks:).
